### ISSUE TITLE
Create button component

### ISSUE THREAD

**Issue by ja-chisholm** [UPEI-Android/group-project-mindjogg#69] opened 2022-01-26 03:26 UTC
## Context
We will need a generic button component for creating buttons, adding backgrounds (if needed) to them, modifying their colour and size, and so on.

## Problem
We do not have such a component. A couple instances of the button component in the prototype are circled below:

![Screenshot 2022-01-25 211814](https://user-images.githubusercontent.com/92540012/151098330-5ba83949-1b79-4842-b978-51a2c9ae5a55.png)
 
As props, the button component should accept:
- An action to be executed on click (likely navigation)
- Text to be displayed
- If a background should be displayed
- Main and secondary colours
- Size
- If a shadow should be shown
- If an image should be displayed, and if so, what image. (e.g. the navigation arrow is an image but "sign up" is not)

## Solution
- [ ] Determine how this component should be implemented
- [ ] Implement it, making sure to generalize wherever possible
- [ ] Complete issue #70 for testing

**Comment by DemiAdisa** [comment] 2022-01-30 18:21
Blocked by #61, will reopen when PR #100  is merged

**Comment by sontushkpaul** [comment] 2022-02-06 04:39
@DemiAdisa We do not need to implement the back arrow button because it comes with stack navigation.

**Comment by sontushkpaul** [comment] 2022-02-06 04:45
@DemiAdisa Please prioritize the implementation of the button components because it is the building block of other screens and components. The issue is blocking #49 and #54

**Comment by DemiAdisa** [comment] 2022-02-06 21:10
Working on the buttons now👌

**Closed as completed** 2022-02-08 13:44 UTC
Labels: enhancement, Environment - Dev, Status - Doing
